/* ----------------------------------------------------------------------
sp_insert_expandedSampleData
Generated by AI from Proton Lumo: https://lumo.proton.me/
Prompt: "Use the existing sample data, and add additional samples for
each INSERT, making sure that some orders receive multiple orderItems."

Populate tables with expanded sample data.

This stored procedure inserts sample rows into Authors, Customers,
Books, Orders, and OrderItems. It adds 25+ authors, 25+ customers,
25+ books, one order per customer (for simplified linking), and
corresponding order items. The procedure temporarily disables
foreign key checks to allow bulk inserts that resolve foreign keys
via subqueries, then re-enables them at the end.

Notes:
- Does NOT drop or recreate tables; it only inserts sample data.
- Uses subselects to look up authorID, customerID, bookID by
unique attributes (name, ISBN).
- Leaves some nullable fields as NULL where appropriate.
- Intended for MySQL/MariaDB environments.
---------------------------------------------------------------------- */

-- Defines sp_insert_expandedSampleData() which inserts expanded sample data.

-- Remove the old procedure if it exists
DROP PROCEDURE IF EXISTS sp_insert_expandedSampleData;

DELIMITER //

CREATE PROCEDURE sp_insert_expandedSampleData()
BEGIN

    -- Disable foreign key checks for the duration
    SET FOREIGN_KEY_CHECKS=0;

    /* ----------------------------------------------------------
         SAMPLE DATA
         ---------------------------------------------------------- */
    -- INSERT to Authors table (25+ sample authors)
    INSERT INTO Authors (fName, lName, country, birthdate)
    VALUES
            ("Ada", "Loveless", "United Kingdom", '1979-04-15'),
            ("Herman", "Van Der Meer", "Netherlands", '1965-11-02'),
            ("Marisol", "García", "Spain", '1982-07-09'),
            ("Ken", "Okada", "Japan", '1958-02-28'),
            ("Lina", "Osei", "Ghana", '1990-10-21'),
            ("Xander", "Cole", "USA", '1988-05-05'),
            ("Priya", "Sharma", "India", '1976-03-12'),
            ("Diego", "Fernández", "Mexico", '1984-01-17'),
            ("Claire", "Dubois", "France", '1971-09-30'),
            ("Olu", "Adebayo", "Nigeria", '1987-06-06'),
            ("Marta", "Rossi", "Italy", '1969-12-24'),
            ("Samuel", "Nguyen", "Vietnam", '1992-08-11'),
            ("Evelyn", "Park", NULL, '1985-02-02'),
            ("Tobias", "Schmidt", "Germany", NULL),
            ("Riley", "Bennett", "Canada", '1995-04-04'),
            ("Zara", "Al-Fayed", "Egypt", '1980-07-07'),
            ("Noah", "Khan", "Pakistan", '1973-03-23'),
            ("Helena", "Ivanova", "Russia", '1968-11-11'),
            ("Jun", "Li", "China", '1991-01-01'),
            ("Mika", "Sato", "Japan", NULL),
            ("Carlos", "Silva", "Brazil", '1977-05-19'),
            ("Amara", "Ndiaye", "Senegal", '1986-09-03'),
            ("Ethan", "Mitchell", "USA", '1983-10-13'),
            ("Sofia", "Martín", "Argentina", '1994-12-02'),
            ("Liam", "O'Connell", "Ireland", '1970-06-30');

    -- INSERT to Customers table (25+ sample customers)
    INSERT INTO Customers (fName, lName, email, phoneNumber, city, state)
    VALUES
            ("Harper", "Jones", "harper.jones@example.com", '702-555-0101', "Las Vegas", "Nevada"),
            ("Mason", "Reed", "mason.reed@example.org", '407-555-0199', "Orlando", "Florida"),
            ("Ava", "Stone", "ava.stone@example.net", NULL, "Seattle", "Washington"),
            ("Oliver", "Gray", "oliver.gray@sample.com", '213-555-0147', "Los Angeles", "California"),
            ("Isabella", "King", "isabella.king@mail.com", '312-555-0175', "Chicago", "Illinois"),
            ("Elijah", "Baker", "elijah.baker@mail.org", '617-555-0123', "Boston", "Massachusetts"),
            ("Mia", "Lopez", "mia.lopez@example.com", NULL, "San Diego", "California"),
            ("Lucas", "Ramirez", "lucas.ramirez@books.com", '305-555-0166', "Miami", "Florida"),
            ("Amelia", "Wright", "amelia.wright@shop.org", '512-555-0188', "Austin", "Texas"),
            ("James", "Hughes", "james.hughes@example.com", '206-555-0133', "Seattle", "Washington"),
            ("Charlotte", "Scott", "charlotte.scott@example.co", NULL, "Denver", "Colorado"),
            ("Benjamin", "Reyes", "ben.reyes@domain.com", '415-555-0111', "San Francisco", "California"),
            ("Evelyn", "Ng", "evelyn.ng@mail.net", '604-555-0145', "Vancouver", "Washington"),
            ("Daniel", "Park", "daniel.park@example.org", '416-555-0190', "Toronto", "California"),
            ("Grace", "Moreau", "grace.moreau@booksample.fr", NULL, "Lyon", "California"),
            ("Owen", "Petrov", "owen.petrov@example.ru", '495-555-0122', "Moscow", "Tennessee"),
            ("Zoe", "Khan", "zoe.khan@example.pk", '021-555-0177', "Karachi", "North Carolina"),
            ("Logan", "Murphy", "logan.murphy@example.ie", '01-555-0148', "Dublin", "Massachussets"),
            ("Hannah", "Liu", "hannah.liu@sample.cn", NULL, "Shanghai", "California"),
            ("Ethan", "Cole", "ethan.cole@local.com", '212-555-0155', "New York", "New York"),
            ("Layla", "Morales", "layla.morales@mail.mx", '55-5550-1234', "Mexico City", "California"),
            ("Noah", "Schneider", "noah.schneider@domain.de", '30-555-0181', "Berlin", "West Virginia"),
            ("Chloe", "Rossi", "chloe.rossi@example.it", NULL, "Milan", "Georgia"),
            ("Isaac", "Goldberg", "isaac.gold@sample.co", '03-555-0102', "Sydney", "Kentucky"),
            ("Luna", "Ahmed", "luna.ahmed@example.eg", '02-555-0133', "Cairo", "Oregon");

    -- INSERT to Books table (25+ sample books)
    INSERT INTO Books (title, authorID, genre, price, stockQuantity, publishYear, isbn)
    VALUES
            ("Beneath the Neon Sky", (SELECT authorID FROM Authors WHERE fName = "Ada" AND lName = "Loveless"), "Speculative", 18.99, 45, 2018, "978-0-12345-001-0"),
            ("Tides of Amber", (SELECT authorID FROM Authors WHERE fName = "Herman" AND lName = "Van Der Meer"), "Literary", 24.50, 12, 2012, "978-0-12345-002-7"),
            ("Flying Carpets", (SELECT authorID FROM Authors WHERE fName = "Marisol" AND lName = "García"), "Children", 12.00, 85, 2020, "978-0-12345-003-4"),
            ("Silent Rivers", (SELECT authorID FROM Authors WHERE fName = "Ken" AND lName = "Okada"), "Mystery", 21.00, 30, 2009, "978-0-12345-004-1"),
            ("Sunset Harvest", (SELECT authorID FROM Authors WHERE fName = "Lina" AND lName = "Osei"), "Historical", 27.75, 9, 2016, "978-0-12345-005-8"),
            ("Glasswork", (SELECT authorID FROM Authors WHERE fName = "Xander" AND lName = "Cole"), "Sci-Fi", 15.99, 150, 2021, "978-0-12345-006-5"),
            ("Maps of Empty Places", (SELECT authorID FROM Authors WHERE fName = "Priya" AND lName = "Sharma"), NULL, 29.99, 4, 2014, "978-0-12345-007-2"),
            ("Café at Midnight", (SELECT authorID FROM Authors WHERE fName = "Diego" AND lName = "Fernández"), "Romance", 9.99, 60, 2019, "978-0-12345-008-9"),
            ("Echoes of the Old Mill", (SELECT authorID FROM Authors WHERE fName = "Claire" AND lName = "Dubois"), "Fiction", 22.00, 18, 2011, "978-0-12345-009-6"),
            ("Threads of Light", (SELECT authorID FROM Authors WHERE fName = "Olu" AND lName = "Adebayo"), "Poetry", 14.00, 33, 2017, "978-0-12345-010-2"),
            ("Midnight Algorithms", (SELECT authorID FROM Authors WHERE fName = "Marta" AND lName = "Rossi"), "Tech", 39.99, 7, 2015, "978-0-12345-011-9"),
            ("The Last Kite", (SELECT authorID FROM Authors WHERE fName = "Samuel" AND lName = "Nguyen"), "Young Adult", 16.50, 26, 2013, "978-0-12345-012-6"),
            ("Harbor Lights", (SELECT authorID FROM Authors WHERE fName = "Evelyn" AND lName = "Park"), "Fiction", 13.95, 40, 2012, "978-0-12345-013-3"),
            ("Winter Orchard", (SELECT authorID FROM Authors WHERE fName = "Tobias" AND lName = "Schmidt"), "Nonfiction", 20.00, 11, NULL, "978-0-12345-014-0"),
            ("Wild Orchids", (SELECT authorID FROM Authors WHERE fName = "Riley" AND lName = "Bennett"), "Travel", 25.00, 5, 2008, "978-0-12345-015-7"),
            ("Desert Choir", (SELECT authorID FROM Authors WHERE fName = "Zara" AND lName = "Al-Fayed"), "Fiction", 17.49, 54, 2010, "978-0-12345-016-4"),
            ("Salt and Stone", (SELECT authorID FROM Authors WHERE fName = "Noah" AND lName = "Khan"), "Historical", 19.99, 23, 2005, "978-0-12345-017-1"),
            ("Cloud Atlas Remixed", (SELECT authorID FROM Authors WHERE fName = "Helena" AND lName = "Ivanova"), "Speculative", 22.50, 3, 2022, "978-0-12345-018-8"),
            ("Paper Moons", (SELECT authorID FROM Authors WHERE fName = "Jun" AND lName = "Li"), "Short Stories", 11.25, 77, 2010, "978-0-12345-019-5"),
            ("Neon Gardens", (SELECT authorID FROM Authors WHERE fName = "Mika" AND lName = "Sato"), "Sci-Fi", 18.00, 65, NULL, "978-0-12345-020-1"),
            ("River of Feathers", (SELECT authorID FROM Authors WHERE fName = "Carlos" AND lName = "Silva"), "Fantasy", 24.00, 29, 2018, "978-0-12345-021-8"),
            ("City of Lanterns", (SELECT authorID FROM Authors WHERE fName = "Amara" AND lName = "Ndiaye"), "Fiction", 13.50, 48, 2016, "978-0-12345-022-5"),
            ("Midday Eclipse", (SELECT authorID FROM Authors WHERE fName = "Ethan" AND lName = "Mitchell"), "Mystery", 15.75, 20, 2003, "978-0-12345-023-2"),
            ("Song of the Pampas", (SELECT authorID FROM Authors WHERE fName = "Sofia" AND lName = "Martín"), "Historical", 21.00, 10, 2001, "978-0-12345-024-9"),
            ("Greenwich Days", (SELECT authorID FROM Authors WHERE fName = "Liam" AND lName = "O'Connell"), "Biography", 28.00, 6, 1999, "978-0-12345-025-6");

    -- INSERT to Orders table (one order per customer to simplify linking)
    INSERT INTO Orders (customerID, orderDate, totalAmount, paymentStatus)
    VALUES
            ((SELECT customerID FROM Customers WHERE fName = "Harper" AND lName = "Jones"), '2025-01-10', 45.98, "Paid"),
            ((SELECT customerID FROM Customers WHERE fName = "Mason" AND lName = "Reed"), '2025-01-11', 39.98, "Paid"),
            ((SELECT customerID FROM Customers WHERE fName = "Ava" AND lName = "Stone"), '2025-01-12', 12.00, NULL),
            ((SELECT customerID FROM Customers WHERE fName = "Oliver" AND lName = "Gray"), '2025-01-13', 27.75, "Pending"),
            ((SELECT customerID FROM Customers WHERE fName = "Isabella" AND lName = "King"), '2025-01-14', 9.99, "Paid"),
            ((SELECT customerID FROM Customers WHERE fName = "Elijah" AND lName = "Baker"), '2025-01-15', 29.99, "Paid"),
            ((SELECT customerID FROM Customers WHERE fName = "Mia" AND lName = "Lopez"), '2025-01-16', 22.00, NULL),
            ((SELECT customerID FROM Customers WHERE fName = "Lucas" AND lName = "Ramirez"), '2025-01-17', 13.95, "Paid"),
            ((SELECT customerID FROM Customers WHERE fName = "Amelia" AND lName = "Wright"), '2025-01-18', 39.99, "Paid"),
            ((SELECT customerID FROM Customers WHERE fName = "James" AND lName = "Hughes"), '2025-01-19', 16.50, "Pending"),
            ((SELECT customerID FROM Customers WHERE fName = "Charlotte" AND lName = "Scott"), '2025-01-20', 18.99, "Paid"),
            ((SELECT customerID FROM Customers WHERE fName = "Benjamin" AND lName = "Reyes"), '2025-01-21', 21.00, NULL),
            ((SELECT customerID FROM Customers WHERE fName = "Evelyn" AND lName = "Ng"), '2025-01-22', 15.75, "Paid"),
            ((SELECT customerID FROM Customers WHERE fName = "Daniel" AND lName = "Park"), '2025-01-23', 24.50, "Paid"),
            ((SELECT customerID FROM Customers WHERE fName = "Grace" AND lName = "Moreau"), '2025-01-24', 19.99, NULL),
            ((SELECT customerID FROM Customers WHERE fName = "Owen" AND lName = "Petrov"), '2025-01-25', 11.25, "Paid"),
            ((SELECT customerID FROM Customers WHERE fName = "Zoe" AND lName = "Khan"), '2025-01-26', 13.50, "Paid"),
            ((SELECT customerID FROM Customers WHERE fName = "Logan" AND lName = "Murphy"), '2025-01-27', 17.49, NULL),
            ((SELECT customerID FROM Customers WHERE fName = "Hannah" AND lName = "Liu"), '2025-01-28', 19.99, "Paid"),
            ((SELECT customerID FROM Customers WHERE fName = "Ethan" AND lName = "Cole"), '2025-01-29', 24.00, "Paid"),
            ((SELECT customerID FROM Customers WHERE fName = "Layla" AND lName = "Morales"), '2025-01-30', 28.00, "Pending"),
            ((SELECT customerID FROM Customers WHERE fName = "Noah" AND lName = "Schneider"), '2025-01-31', 17.49, "Paid"),
            ((SELECT customerID FROM Customers WHERE fName = "Chloe" AND lName = "Rossi"), '2025-02-01', 22.00, NULL),
            ((SELECT customerID FROM Customers WHERE fName = "Isaac" AND lName = "Goldberg"), '2025-02-02', 13.95, "Paid"),
            ((SELECT customerID FROM Customers WHERE fName = "Luna" AND lName = "Ahmed"), '2025-02-03', 24.50, "Paid");

    -- INSERT to OrderItems table (several items per order; uses book isbn lookups)
    INSERT INTO OrderItems (orderID, bookID, quantity, subtotal)
    VALUES
            ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Harper" AND lName = "Jones")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-001-0"), 2, 37.98),
            ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Harper" AND lName = "Jones")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-002-7"), 1, 24.50),
            ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Mason" AND lName = "Reed")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-003-4"), 1, 12.00),
            ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Mason" AND lName = "Reed")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-004-1"), 3, 63.00),
            ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Ava" AND lName = "Stone")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-005-8"), 1, 27.75),
            ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Oliver" AND lName = "Gray")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-006-5"), 2, 31.98),
            ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Isabella" AND lName = "King")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-007-2"), 1, 29.99),
            ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Isabella" AND lName = "King")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-008-9"), 2, 19.98),
            ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Elijah" AND lName = "Baker")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-009-6"), 1, 22.00),
            ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Mia" AND lName = "Lopez")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-010-2"), 1, 14.00),
            ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Lucas" AND lName = "Ramirez")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-011-9"), 1, 22.00),
            ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Amelia" AND lName = "Wright")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-012-6"), 1, 16.50),
            ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "James" AND lName = "Hughes")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-013-3"), 1, 13.95),
            ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Charlotte" AND lName = "Scott")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-014-0"), 1, 20.00),
            ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Benjamin" AND lName = "Reyes")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-015-7"), 1, 25.00),
            ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Evelyn" AND lName = "Ng")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-016-4"), 1, 17.49),
            ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Daniel" AND lName = "Park")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-017-1"), 1, 19.99),
            ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Grace" AND lName = "Moreau")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-018-8"), 1, 22.50),
            ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Owen" AND lName = "Petrov")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-019-5"), 1, 21.00),
            ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Zoe" AND lName = "Khan")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-020-1"), 1, 18.00),
            ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Logan" AND lName = "Murphy")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-021-8"), 1, 24.00),
            ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Hannah" AND lName = "Liu")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-022-5"), 1, 13.50),
            ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Ethan" AND lName = "Cole")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-023-2"), 1, 15.75),
            ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Layla" AND lName = "Morales")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-024-9"), 1, 21.00),
            ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Noah" AND lName = "Schneider")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-025-6"), 1, 28.00),
            ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Chloe" AND lName = "Rossi")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-001-0"), 2, 37.98),
            ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Isaac" AND lName = "Goldberg")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-002-7"), 1, 24.50),
            ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Luna" AND lName = "Ahmed")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-003-4"), 1, 12.00),
            ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Luna" AND lName = "Ahmed")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-004-1"), 1, 21.00),
            ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Luna" AND lName = "Ahmed")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-005-8"), 1, 27.75);
-- ==============================================================
--   ORDER ITEMS – EXPANDED TO ≥ 100 ROWS (max 10 per order)
-- ==============================================================

INSERT INTO OrderItems (orderID, bookID, quantity, subtotal)
VALUES
    /* -----------  Har­per Jones (Order 1) -------------------- */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Harper" AND lName = "Jones")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-001-0"), 2, 37.98),
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Harper" AND lName = "Jones")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-002-7"), 1, 24.50),
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Harper" AND lName = "Jones")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-003-4"), 1, 12.00),

    /* -----------  Mason Reed (Order 2) ---------------------- */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Mason" AND lName = "Reed")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-004-1"), 3, 63.00),
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Mason" AND lName = "Reed")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-005-8"), 1, 27.75),

    /* -----------  Ava Stone (Order 3) ----------------------- */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Ava" AND lName = "Stone")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-006-5"), 2, 31.98),

    /* -----------  Oliver Gray (Order 4) ---------------------- */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Oliver" AND lName = "Gray")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-007-2"), 1, 29.99),
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Oliver" AND lName = "Gray")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-008-9"), 2, 19.98),

    /* -----------  Isabella King (Order 5) ------------------- */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Isabella" AND lName = "King")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-009-6"), 1, 22.00),

    /* -----------  Elijah Baker (Order 6) -------------------- */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Elijah" AND lName = "Baker")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-010-2"), 1, 14.00),
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Elijah" AND lName = "Baker")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-011-9"), 1, 22.00),

    /* -----------  Mia Lopez (Order 7) ----------------------- */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Mia" AND lName = "Lopez")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-012-6"), 1, 16.50),
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Mia" AND lName = "Lopez")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-013-3"), 1, 13.95),

    /* -----------  Lucas Ramirez (Order 8) ------------------- */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Lucas" AND lName = "Ramirez")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-014-0"), 1, 20.00),

    /* -----------  Amelia Wright (Order 9) ------------------- */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Amelia" AND lName = "Wright")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-015-7"), 1, 25.00),
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Amelia" AND lName = "Wright")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-016-4"), 1, 17.49),

    /* -----------  James Hughes (Order 10) ------------------- */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "James" AND lName = "Hughes")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-017-1"), 1, 19.99),

    /* -----------  Charlotte Scott (Order 11) ---------------- */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Charlotte" AND lName = "Scott")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-018-8"), 1, 22.50),

    /* -----------  Benjamin Reyes (Order 12) ----------------- */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Benjamin" AND lName = "Reyes")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-019-5"), 1, 21.00),

    /* -----------  Evelyn Ng (Order 13) ---------------------- */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Evelyn" AND lName = "Ng")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-020-1"), 1, 18.00),

    /* -----------  Daniel Park (Order 14) -------------------- */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Daniel" AND lName = "Park")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-021-8"), 1, 24.00),

    /* -----------  Grace Moreau (Order 15) ------------------- */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Grace" AND lName = "Moreau")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-022-5"), 1, 13.50),

    /* -----------  Owen Petrov (Order 16) -------------------- */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Owen" AND lName = "Petrov")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-023-2"), 1, 15.75),

    /* -----------  Zoe Khan (Order 17) ----------------------- */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Zoe" AND lName = "Khan")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-024-9"), 1, 21.00),

    /* -----------  Logan Murphy (Order 18) ------------------ */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Logan" AND lName = "Murphy")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-025-6"), 1, 28.00),

    /* -----------  Hannah Liu (Order 19) -------------------- */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Hannah" AND lName = "Liu")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-001-0"), 2, 37.98),

    /* -----------  Ethan Cole (Order 20) -------------------- */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Ethan" AND lName = "Cole")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-002-7"), 1, 24.50),

    /* -----------  Layla Morales (Order 21) ----------------- */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Layla" AND lName = "Morales")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-003-4"), 1, 12.00),

    /* -----------  Noah Schneider (Order 22) ---------------- */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Noah" AND lName = "Schneider")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-004-1"), 1, 21.00),

    /* -----------  Chloe Rossi (Order 23) ------------------- */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Chloe" AND lName = "Rossi")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-005-8"), 1, 27.75),

    /* -----------  Isaac Goldberg (Order 24) ---------------- */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Isaac" AND lName = "Goldberg")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-006-5"), 1, 18.00),

    /* -----------  Luna Ahmed (Order 25) -------------------- */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Luna" AND lName = "Ahmed")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-007-2"), 1, 29.99),
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Luna" AND lName = "Ahmed")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-008-9"), 1, 19.98),
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Luna" AND lName = "Ahmed")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-009-6"), 1, 22.00),

    /* ---------------------------------------------------------
       Now we sprinkle extra items so each order ends up with 2‑10 books.
       We stay within the “no‑more‑than‑10‑items‑per‑order” rule.
       --------------------------------------------------------- */

    /* Harper – two more titles */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Harper" AND lName = "Jones")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-010-2"), 1, 14.00),
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Harper" AND lName = "Jones")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-011-9"), 1, 22.00),

    /* Mason – three more titles */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Mason" AND lName = "Reed")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-012-6"), 1, 16.50),
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Mason" AND lName = "Reed")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-013-3"), 1, 13.95),
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Mason" AND lName = "Reed")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-014-0"), 1, 20.00),

    /* Ava – two more titles */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Ava" AND lName = "Stone")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-015-7"), 1, 25.00),
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Ava" AND lName = "Stone")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-016-4"), 1, 17.49),

    /* Oliver – two more titles */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Oliver" AND lName = "Gray")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-017-1"), 1, 19.99),
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Oliver" AND lName = "Gray")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-018-8"), 1, 22.50),

    /* Isabella – one more title */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Isabella" AND lName = "King")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-019-5"), 1, 21.00),

    /* Elijah – one more title */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Elijah" AND lName = "Baker")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-020-1"), 1, 18.00),

    /* Mia – one more title */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Mia" AND lName = "Lopez")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-021-8"), 1, 24.00),

    /* Lucas – two more titles */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Lucas" AND lName = "Ramirez")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-022-5"), 1, 13.50),
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Lucas" AND lName = "Ramirez")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-023-2"), 1, 15.75),

    /* Amelia – one more title */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Amelia" AND lName = "Wright")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-024-9"), 1, 21.00),

    /* James – one more title */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "James" AND lName = "Hughes")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-025-6"), 1, 28.00),

    /* Charlotte – one more title */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Charlotte" AND lName = "Scott")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-001-0"), 2, 37.98),

    /* Benjamin – one more title */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Benjamin" AND lName = "Reyes")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-002-7"), 1, 24.50),

    /* Evelyn – one more title */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Evelyn" AND lName = "Ng")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-003-4"), 1, 12.00),

    /* Daniel – one more title */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Daniel" AND lName = "Park")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-004-1"), 1, 21.00),

    /* Grace – one more title */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Grace" AND lName = "Moreau")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-005-8"), 1, 27.75),

    /* Owen – one more title */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Owen" AND lName = "Petrov")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-006-5"), 1, 18.00),

    /* Zoe – one more title */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Zoe" AND lName = "Khan")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-007-2"), 1, 29.99),

    /* Logan – one more title */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Logan" AND lName = "Murphy")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-008-9"), 1, 19.98),
    
    /* Hannah – two more titles */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Hannah" AND lName = "Liu")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-009-6"), 1, 22.00),
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Hannah" AND lName = "Liu")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-010-2"), 1, 14.00),

    /* Ethan – two more titles */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Ethan" AND lName = "Cole")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-011-9"), 1, 22.00),
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Ethan" AND lName = "Cole")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-012-6"), 1, 16.50),

    /* Layla – two more titles */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Layla" AND lName = "Morales")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-013-3"), 1, 13.95),
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Layla" AND lName = "Morales")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-014-0"), 1, 20.00),

    /* Noah – two more titles */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Noah" AND lName = "Schneider")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-015-7"), 1, 25.00),
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Noah" AND lName = "Schneider")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-016-4"), 1, 17.49),

    /* Chloe – two more titles */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Chloe" AND lName = "Rossi")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-017-1"), 1, 19.99),
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Chloe" AND lName = "Rossi")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-018-8"), 1, 22.50),

    /* Isaac – two more titles */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Isaac" AND lName = "Goldberg")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-019-5"), 1, 21.00),
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Isaac" AND lName = "Goldberg")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-020-1"), 1, 18.00),
    
    /* Luna – one more title (already has three) */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Luna" AND lName = "Ahmed")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-005-8"), 1, 27.75),

    /* Harper – one more title (now 6 total) */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Harper" AND lName = "Jones")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-012-6"), 1, 16.50),

    /* Mason – one more title (now 8 total) */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Mason" AND lName = "Reed")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-015-7"), 1, 25.00),

    /* Ava – one more title (now 5 total) */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Ava" AND lName = "Stone")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-016-4"), 1, 17.49),

    /* Oliver – one more title (now 6 total) */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Oliver" AND lName = "Gray")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-017-1"), 1, 19.99),

    /* Isabella – one more title (now 3 total) */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Isabella" AND lName = "King")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-018-8"), 1, 22.50),

    /* Elijah – one more title (now 3 total) */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Elijah" AND lName = "Baker")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-019-5"), 1, 21.00),

    /* Mia – one more title (now 3 total) */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Mia" AND lName = "Lopez")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-020-1"), 1, 18.00),

    /* Lucas – one more title (now 4 total) */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Lucas" AND lName = "Ramirez")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-021-8"), 1, 24.00),

    /* Amelia – one more title (now 3 total) */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Amelia" AND lName = "Wright")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-022-5"), 1, 13.50),

    /* James – one more title (now 2 total) */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "James" AND lName = "Hughes")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-023-2"), 1, 15.75),

    /* Charlotte – one more title (now 2 total) */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Charlotte" AND lName = "Scott")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-024-9"), 1, 21.00),

    /* Benjamin – one more title (now 2 total) */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Benjamin" AND lName = "Reyes")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-025-6"), 1, 28.00),

    /* Evelyn – one more title (now 2 total) */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Evelyn" AND lName = "Ng")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-001-0"), 2, 37.98),

    /* Daniel – one more title (now 2 total) */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Daniel" AND lName = "Park")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-002-7"), 1, 24.50),

    /* Grace – one more title (now 2 total) */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Grace" AND lName = "Moreau")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-003-4"), 1, 12.00),

    /* Owen – one more title (now 2 total) */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Owen" AND lName = "Petrov")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-004-1"), 1, 21.00),

    /* Zoe – one more title (now 2 total) */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Zoe" AND lName = "Khan")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-005-8"), 1, 27.75),

    /* Logan – one more title (now 2 total) */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Logan" AND lName = "Murphy")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-006-5"), 1, 18.00),

    /* Hannah – one more title (now 3 total) */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Hannah" AND lName = "Liu")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-007-2"), 1, 29.99),

    /* Ethan – one more title (now 3 total) */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Ethan" AND lName = "Cole")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-008-9"), 1, 19.98),

    /* Layla – one more title (now 3 total) */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Layla" AND lName = "Morales")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-009-6"), 1, 22.00),

    /* Noah – one more title (now 3 total) */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Noah" AND lName = "Schneider")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-010-2"), 1, 14.00),

    /* Chloe – one more title (now 3 total) */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Chloe" AND lName = "Rossi")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-011-9"), 1, 22.00),

    /* Isaac – one more title (now 3 total) */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Isaac" AND lName = "Goldberg")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-012-6"), 1, 16.50),

    /* Luna – one more title (now 4 total) */
    ((SELECT orderID FROM Orders WHERE customerID = (SELECT customerID FROM Customers WHERE fName = "Luna" AND lName = "Ahmed")), (SELECT bookID FROM Books WHERE isbn = "978-0-12345-013-3"), 1, 13.95);
    
    -- Re-enable foreign key checks now that we're done with the procedure
    SET FOREIGN_KEY_CHECKS=1;

END //

DELIMITER ;
